version: '3'
services:
  postgres:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
  api:
    build: .
    dockerfile: ./api/Dockerfile
    env_file: .env
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - PG_HOST=postgres
      - PG_USERNAME=postgres
    volumes:
      - ./api:/app
    ports:
      - 4000:4000
    links:
      - postgres